# XMaintenance plugin configuration
# Copyright (C) 2020 Fritx22

# Plugin prefix for all the configurable messages
plugin-prefix: '&6[XMaintenance]&r '

# This will be the name of the fake outdated server version
# It's red by default
ping-text: 'Maintenance'

# Enable bypass permission. The permission is "xmaintenance.bypass"
# Note that emergency mode has no bypass
enable-bypass: true

# Whether to allow players to execute the plugin command
# The permission for the plugin command is "xmaintenance.admin"
# For security reasons the emergency mode can't be enabled by a player
allow-players: true

# Players will be kicked with this message if maintenance mode is enabled
kick-message: '&cWe are under maintenance, please try again later.'

# Kick message shown when staff enables the emergency maintenance mode
emergency-kick-message: '&cThe staff enabled the emergency maintenance mode.'

# All the players that have the permission "xmaintenance.admin" will see this messages
admin-alert-messages:
  - '&6&m----------------------------------------'
  - '%prefix%&7The player &c%player% &7tried to join.'
  - '&6&m----------------------------------------'

# Message used when a player tries to enable/disable the maintenance mode, but it's already enabled/disabled.
already-status: '%prefix%&7The maintenance mode is already %status%&7.'

# If enabled, this will set custom online and maximum players
# while the server is under maintenance
players-editor:
  max:
    enable: true
    value: 0

  online:
    enable: true
    value: 0

# If enabled, this will set a custom message
# in the player list while the server is under
# maintenance
players-hover:
  enable: true
  messages:
    - '&7XMaintenance - Default message'
    - '&aYou can add multiple lines!'

# Integer number used by the client to know if the server is the same version, it's outdated, or it's a newer version
# More information: https://minecraft.gamepedia.com/Protocol_version
fake-version-protocol-number: -503
